version: "3.9"
services:
  designer:
    build:
      context: .
      args:
        - WORKSPACE_NAME=designer
        - PORT=3000
      network: host  
    network_mode: host    
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123abc
      - sandbox=true
      - PREVIEW_URL=http://localhost:3009
      - PUBLISH_URL=http://runner:3009
    command: yarn designer dev
    depends_on:
      - redis
      - runner
  runner:
    build:
      context: .
      args:
        - WORKSPACE_NAME=runner
        - PORT=3009
        network: host  
    network_mode: host
    ports:
      - "3009:3009"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123abc
      - sandbox=true
      - PREVIEW_MODE=true
    command: yarn runner dev
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123abc
    network_mode: host
    ports:
      - "6379:6379"
