# This is a basic workflow that is manually triggered

name: Fork sync by dispatch (from xgovformbuilder)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "ref"
        required: false
      sha:
        description: 'triggered'
        required: false

jobs:
  xgovformbuilder-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          sha: ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.ref }}
