name: Smoke Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build the stack
        run: docker-compose up -d
      - name: Check designer running
        run: |
          sleep 180
          docker ps
      - name: Check containers are accessible
        run: |
          export DESIGNER_CID=$(docker ps | grep digital-form-builder | grep designer | awk '{ print $1}')
          export DESIGNER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DESIGNER_CID)
          export RUNNER_CID=$(docker ps | grep digital-form-builder | grep runner | awk '{ print $1}')
          export RUNNER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $RUNNER_CID)
          echo "Designer URL: http://$DESIGNER_IP:3000/"
          echo "Runner URL: http://$RUNNER_IP:3009/"
          curl -v -s --retry 10 --retry-connrefused "http://localhost:3000/"
          curl -v -s --retry 10 --retry-connrefused "http://localhost:3009/"
      - name: Smoke Tests
        run: |
          echo "TODO Run smoke tests"
      - name: Teardown
        run: docker-componse down
