name: Smoke Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn --immutable
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: |
          dcoker ps
          curl -v -s --retry 10 --retry-connrefused http://localhost:3000/
      - name: Smoke Tests
        run: |
          cd smoke-tests/designer
          yarn run smoke-test
      - name: Teardown
        run: docker-componse down
