name: Smoke Tests
on: 
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
 workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Setup yarn
        run: |
          yarn add node-gyp
          sudo apt update && sudo apt install yarn
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.0
      - name: Smoke Tests
        run: |
         cd smoke-tests/designer
         yarn run smoke-test
      - name: Teardown
        run: docker-componse down
