name: Smoke Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build the stack
        run: docker-compose up -d
      - name: Check containers are accessible
        run: |
          export DESIGNER_IP=$(docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq) | grep digital-form-builder_designer | awk '{print $3}')
          export RUNNER_IP=$(docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq) | grep digital-form-builder_runner | awk '{print $3}')
          echo "Designer URL: http://$DESIGNER_IP:3000/"
          echo "Runner URL: http://$RUNNER_IP:3000/"
          #curl -v -s --retry 10 --retry-connrefused "http://$DESIGNER_IP:3000/"
          #curl -v -s --retry 10 --retry-connrefused "http://$RUNNER_IP:3009/"
      - name: Smoke Tests
        run: |
          cd smoke-tests/designer
          yarn --immutable
          yarn run smoke-test
      - name: Teardown
        run: docker-componse down
