name: Smoke Tests
on: 
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
 workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'node:12-alpine3.12'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install
  
      - name: Smoke Tests
        run: |
         cd smoke-tests/designer
         yarn run smoke-test
      - name: Teardown
        run: docker-componse down
