# This is a basic workflow to help you get started with Actions

name: sync-fork

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '* * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
    # Step 2: Pull upstream https://github.com/XGovFormBuilder/digital-form-builder and push
    - run: |
        echo "Setup git config"
        git config --global advice.detachedHead false
        if [ -d "xgov" ]; then rm -Rf xgov; else mkdir xgov; fi
        cd xgov && git clone --depth 1 https://github.com/XGovFormBuilder/digital-form-builder.git && cd digital-form-builder
        export LAST_COMMIT_AUTHOR=$(echo $(git log -1 --pretty=format:"%an"))
        export LAST_COMMIT_AUTHOR_EMAIL=$(echo $(git log -1 --pretty=format:"%ae"))
        export LAST_COMMIT_MESSAGE=$(echo $(git log -1 --pretty='%s'))
        echo "Processing -[author: $LAST_COMMIT_AUTHOR, author email: $LAST_COMMIT_AUTHOR_EMAIL, last commit message: $LAST_COMMIT_MESSAGE]"
        git config user.name $LAST_COMMIT_AUTHOR
        git config user.email $LAST_COMMIT_AUTHOR_EMAIL
        echo "Config done"
        git fetch --all
        echo "Pull latest from XGovFormBuilder"
        git pull --allow-unrelated-histories https://github.com/XGovFormBuilder/digital-form-builder
        git commit --amend -m " Updated to $LAST_COMMIT_MESSAGE"
        git push -u
        echo "Sync completed"
#     - name: Pull upstream changes
#       id: sync
#       uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
#       with:
#         upstream_repository: XGovFormBuilder/digital-form-builder
#         upstream_branch: master
#         target_branch: master
#         git_pull_args: --allow-unrelated-histories
#     # Step 3: Display a message if 'sync' step had new commits (simple test)
#     - name: Check for new commits
#       if: steps.sync.outputs.has_new_commits
#       run: echo "There were new commits."

#     # Step 4: Print a helpful timestamp for your records (not required, just nice)
#     - name: Timestamp
#       run: date  
