# This is a basic workflow to help you get started with Actions

name: sync-fork

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - run: |
        cd digital-form-builder-1
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git_log=`git ls-remote git url  master`
        git_commitId = git_log | cut -d " " -f1
        echo $git_commitId

        #cd /workspace
        git_log_verify = `git rev-parse HEAD`
        echo $git_log_verify

        if $git_commitId =$git_log_verify then
        cd /workspace
          git_authorName=`git log --pretty=format:"%an"`;
          echo $git_authorName
        fi
        #git pull --rebase https://github.com/XGovFormBuilder/digital-form-builder
        #git push -u -f
        
#     - name: Pull upstream changes
#       id: sync
#       uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
#       with:
#         upstream_repository: XGovFormBuilder/digital-form-builder
#         upstream_branch: master
#         target_branch: master
#         git_push_args: --force
#         git_pull_args: --rebase


#     # Step 3: Display a message if 'sync' step had new commits (simple test)
#     - name: Check for new commits
#       if: steps.sync.outputs.has_new_commits
#       run: echo "There were new commits."

#     # Step 4: Print a helpful timestamp for your records (not required)
#     - name: Timestamp
#       run: date
